## Lire le jeu de données

In [1]:
import pandas as pd
# lire le jeu de donné
df = pd.read_csv("../data/brut/offres_combinees.csv")
df.head()

,titre,entreprise,categorie,ville,contrat,date_publication,description,lien
0,Technicien Soufflage,groupe-topinter,"Maintenance, Entretien, Contrôle | Industrie M...",Dakar (seneg...,NaN,2026-04-21,"Missions•\tInstaller, régler et contrôler les ...",https://senjob.com/sn/jobseekers/technicien-so...
1,COMMERCIAL VSR,groupe-topinter,"Commercial, Vente, Business developpement | Di...",Dakar (seneg...,NaN,2026-04-21,Missions Principales: vente de produits alimen...,https://senjob.com/sn/jobseekers/commercial-vs...
2,Développeur Fullstack Java/Vue js,NaN,"Informatique, Télécoms, Réseaux | Industrie In...",Dakar,NaN,2026-04-01,"Description de l'entrepriseImplantée à Dakar, ...",https://senjob.com/sn/jobseekers/développeur-f...
3,04 Assistant(e)s Techniques SAME (MATAM),NaN,"Administration, Services généraux | Qualité, S...",matam,NaN,2026-04-24,NOM Assistant (e) technique ClimateRiceRÔLE As...,https://senjob.com/sn/jobseekers/04-assistant-...
4,CHEF DE SECTEUR JUNIOR,groupe-topinter,"Commercial, Vente, Business developpement | In...",dakar senega...,NaN,2026-04-08,II.\tMISSION PRINCIPALELe Chef de secteur Juni...,https://senjob.com/sn/jobseekers/chef-de-secte...

## Les info de données

In [2]:
df.shape

(4990, 8)

In [3]:
# le statistique 
df.describe()

,titre,entreprise,categorie,ville,contrat,date_publication,description,lien
count,4990,4725,4677,4990,1414,4960,4988,4990
unique,4114,1072,371,106,39,200,4787,4904
top,Comptable,EXPAT-DAKAR.COM,Agences de recrutement,Dakar,cdd,2026-04-23,NOM Assistant (e) technique ClimateRiceRÔLE As...,https://senjob.com/sn/jobseekers/04-assistant-...
freq,29,186,521,4322,600,188,12,12

In [4]:
#information de données
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4990 entries, 0 to 4989
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   titre             4990 non-null   str
 1   entreprise        4725 non-null   str
 2   categorie         4677 non-null   str
 3   ville             4990 non-null   str
 4   contrat           1414 non-null   str
 5   date_publication  4960 non-null   str
 6   description       4988 non-null   str
 7   lien              4990 non-null   str
dtypes: str(8)
memory usage: 312.0 KB

## Les valeurs manquantes

In [5]:
df.isnull().sum()

titre                  0
entreprise           265
categorie            313
ville                  0
contrat             3576
date_publication      30
description            2
lien                   0
dtype: int64

## les doublons

In [6]:
df.duplicated().sum()

np.int64(83)

## types de données

In [7]:
df['ville'].value_counts().head(20)

ville
Dakar                                                                4322
Dakar, Sénégal                                                        222
Dakar -                                                                76
Dakar - Diourbel - Fatick - Kaffrine - Kaolack - Kédougou - Kolda      48
Thiès                                                                  27
International                                                          23
Niamey                                                                 22
Abidjan                                                                21
Dakar & International                                                  14
matam                                                                  12
zone rural...                                                          10
SALY (MBOU...                                                          10
Dakar (seneg...                                                         9
Thiès, Sénégal                                                          9
dakar                                                                   8
Lomé                                                                    8
Kaolack                                                                 6
Louga                                                                   6
M'bour                                                                  4
Bamako                                                                  4
Name: count, dtype: int64

In [8]:
df['contrat'].value_counts()

contrat
cdd                                                                            600
CDD                                                                            217
cdi                                                                            185
CDI                                                                            112
internship                                                                      81
Stage                                                                           43
CDI, CDD - Freelance                                                            36
Prestation de Services                                                          26
Freelance                                                                       26
CDI & CDD                                                                       18
freelance                                                                        7
CDD & Stage                                                                      7
CDI - Freelance                                                                  6
Temps partiel                                                                    5
Statutaire                                                                       5
apprenticeship_alternation                                                       4
CDD & Freelance                                                                  4
CDD & Intérim                                                                    4
CDI, CDD, Intérim, Stage, Freelance, Alternance, Temps partiel & Statutaire      3
CDD, Stage & Freelance                                                           3
CDI, CDD & Intérim                                                               2
CDI, CDD & Freelance                                                             2
CDD, Intérim, Stage, Alternance & Temps partiel                                  2
Intérim                                                                          1
CDI - CDD                                                                        1
Stage, Freelance & Temps partiel                                                 1
Alternance                                                                       1
Intérim, Stage, Freelance, Alternance & Statutaire                               1
Freelance & Alternance                                                           1
CDD, Intérim & Temps partiel                                                     1
CDD, Intérim, Stage, Freelance, Alternance & Temps partiel                       1
Intérim, Freelance & Temps partiel                                               1
CDI, CDD, Stage, Freelance & Temps partiel                                       1
Stage, Alternance & Temps partiel                                                1
CDI, Intérim & Temps partiel                                                     1
CDI, CDD & Stage                                                                 1
CDD & Temps partiel                                                              1
CDD, Freelance & Temps partiel                                                   1
CDI, CDD & Temps partiel                                                         1
Name: count, dtype: int64

In [9]:
df['categorie'].value_counts().head(20)

categorie
Agences de recrutement                       521
Organisations non-gouvernementales (ONG)     492
Organismes internationaux                    225
Gestion des ressources humaines              214
Vente en ligne                               196
Travail temporaire - Intérim                 150
Banques                                       99
Enseignement supérieur - Université           93
Administrations                               81
Industries                                    72
Management                                    67
Informatique                                  58
Agences de communication                      56
Prestation de service                         56
Transit                                       51
Informatique, nouvelles technologies          48
Bureaux d'études - Conseils - Consultants     47
Equipements médicaux                          46
Centres d'appels                              45
Produits laitiers                             42
Name: count, dtype: int64

In [10]:
df['date_publication'].value_counts().head(20)

date_publication
2026-04-23    188
2025-12-15    108
2026-04-07     94
2026-04-13     90
2025-10-10     75
2026-03-09     69
2025-10-02     66
2025-10-27     63
2025-06-02     62
2026-03-02     61
2025-11-06     60
2025-02-26     60
2026-02-09     58
2025-03-06     57
2025-12-31     55
2025-05-13     55
2025-09-25     54
2025-02-13     54
2025-01-21     54
2025-10-16     52
Name: count, dtype: int64

In [11]:
df_propre = pd.read_csv("../data/propre/offres_nettoyees.csv")
df_propre.head()

,titre,entreprise,secteur,ville,contrat,date_publication,description,lien
0,Technicien Soufflage,groupe-topinter,"Maintenance, Entretien, Contrôle | Industrie M...",Dakar,Non précisé,2026-04-21,"Missions•\tInstaller, régler et contrôler les ...",https://senjob.com/sn/jobseekers/technicien-so...
1,COMMERCIAL VSR,groupe-topinter,"Commercial, Vente, Business developpement | Di...",Dakar,Non précisé,2026-04-21,Missions Principales: vente de produits alimen...,https://senjob.com/sn/jobseekers/commercial-vs...
2,Développeur Fullstack Java/Vue js,Confidentiel,"Informatique, Télécoms, Réseaux | Industrie In...",Dakar,Non précisé,2026-04-01,"Description de l'entrepriseImplantée à Dakar, ...",https://senjob.com/sn/jobseekers/développeur-f...
3,04 Assistant(e)s Techniques SAME (MATAM),Confidentiel,"Administration, Services généraux | Qualité, S...",Matam,Non précisé,2026-04-24,NOM Assistant (e) technique ClimateRiceRÔLE As...,https://senjob.com/sn/jobseekers/04-assistant-...
4,CHEF DE SECTEUR JUNIOR,groupe-topinter,"Commercial, Vente, Business developpement | In...",Dakar,Non précisé,2026-04-08,II.\tMISSION PRINCIPALELe Chef de secteur Juni...,https://senjob.com/sn/jobseekers/chef-de-secte...

In [12]:
df_propre.isnull().sum()

titre               0
entreprise          0
secteur             0
ville               0
contrat             0
date_publication    0
description         0
lien                0
dtype: int64

In [14]:
df_propre.duplicated().sum()

np.int64(0)

In [15]:
df_propre['contrat'].value_counts()

contrat
Non précisé               3511
CDD                        829
CDI                        300
Stage                      127
CDI/CDD                     65
Freelance                   35
Prestation de services      26
Alternance                   5
Temps partiel                5
Intérim                      1
Name: count, dtype: int64

In [ ]:
df_propre['ville'].value_counts().head(20)